<p>Trzecią i ostatnią część artykułu poświęcam rzadkiemu ale bardzo trudnemu w analizie problemowi, który może pojawić się w czasie adaptacji API w wykorzystaniem TaskCompletionSource.</p>
<p>Zacznę od takiego niewinnego kawałku kodu:</p>
<div class="code"><pre class="prettyprint lang-cs">class Adapter
{
    public Task&lt;int&gt; GetNextInt()
    {
        var api = new CallbacksApi();
        var taskCompletionSource = new TaskCompletionSource&lt;int&gt;();
    
        api.GetNextInt((result, exception) =&gt;
        {
            if (exception != null)
            {
                taskCompletionSource.SetException(exception);
            }
            else
            {
                taskCompletionSource.SetResult(result);
            }
        });
        
        return taskCompletionSource.Task;
    }
}</pre></div>
<p>Kod wydaje się poprawny. Co lepsze będzie działać w czasie testów dymnych, prawdopodobnie przejdzie testy funkcjonalne. Kod ten może jednak powodować pojawianie się błędów typu: &quot;Ta operacja czasami nie kończy się przez pół godziny&quot;, &quot;aplikacja chodzi wolno&quot; albo &quot;program się zawiesza&quot;. Co gorsza nikt nie będzie w stanie dostarczyć powtarzalnego scenariusza.</p>
<p>Winnym okazuje się być Garbage Collector, który może w tym przypadku błędnie stwierdzić, że nikt nie potrzebuje obiektu CallbacksApi, bo nikt nie posiada do niego referencji.</p>
<img src="http://static.szogun1987.pl/img/events-and-tasks/ObjectReferences.svg" alt="Referencje pomiędzy obiektami" class="img-responsive" />
<p>Pierwszym sposobem &quot;obejścia&quot; tego problemu może być &quot;przytrzymanie&quot; referencji do API w jakimś obiekcie, który żyje dłużej. W kodzie powyżej może być to klasa obiekt typu Adapter.</p>
<div class="code"><pre class="prettyprint lang-cs">class Adapter
{
    private CallbacksApi _api = new CallbacksApi();
    public Task&lt;int&gt; GetNextInt()
    {
        var taskCompletionSource = new TaskCompletionSource&lt;int&gt;();
    
        _api.GetNextInt((result, exception) =&gt;
        {
            if (exception != null)
            {
                taskCompletionSource.SetException(exception);
            }
            else
            {
                taskCompletionSource.SetResult(result);
            }
        });
        
        return taskCompletionSource.Task;
    }
}</pre></div>
<p>Sprawa się komplikuje gdy nowe CallbacksApi musi być tworzone z każdym wywołaniem GetNextInt. Brzydkim ale szybkim obejściem tego problemu jest użycie kolekcji:</p>
<div class="code"><pre class="prettyprint lang-cs">class Adapter
{
    private List&lt;CallbacksApi&gt; _apiReferences = new List&lt;CallbacksApi&gt;();
    private object _apiReferencesLockRoot = new object();
    public Task&lt;int&gt; GetNextInt()
    {
        var api = new CallbacksApi();
        var taskCompletionSource = new TaskCompletionSource&lt;int&gt;();
        lock(_apiReferencesLockRooti)
        {
            _apiReferences.Add(api);
        }
    
        api.GetNextInt((result, exception) =&gt;
        {
            lock(_apiReferencesLockRooti)
            {
                _apiReferences.Add(api);
            }
            if (exception != null)
            {
                taskCompletionSource.SetException(exception);
            }
            else
            {
                taskCompletionSource.SetResult(result);
            }
        });
        
        return taskCompletionSource.Task;
    }
}</pre></div>
<p>Ten kod działa ale wszyscy się chyba zgodzą że najładniejszy to on nie jest. W dodatku jeżeli referencja do obiektu typu Adapter nie jest nigdzie przetrzymywana przez dłuższy czas to powyższe rozwiązania i tak nie zadziałają. Na szczęście Microsoft pomyślał o tym problemie i TaskCompletionSource posiada dodatkowy parametr konstruktora &quot;state&quot;, którego można przekazać cokolwiek. Obiekt ten jest przypisany do właściwości AsyncState wynikowego Taska, przez co GC zostawi go w spokoju.</p>
<div class="code"><pre class="prettyprint lang-cs">class Adapter
{
    public Task&lt;int&gt; GetNextInt()
    {
        var api = new CallbacksApi();
        var taskCompletionSource = new TaskCompletionSource&lt;int&gt;(api);
    
        api.GetNextInt((result, exception) =&gt;
        {
            if (exception != null)
            {
                taskCompletionSource.SetException(exception);
            }
            else
            {
                taskCompletionSource.SetResult(result);
            }
        });
        
        return taskCompletionSource.Task;
    }
}</pre></div>

<p>Kod klas, które stworzyłem na potrzeby tego wpisu znajduje się w tym punkie <a href="https://github.com/szogun1987/events-and-tasks/tree/master/src/Szogun1987.EventsAndTasks/Callbacks/NeverCalledback">Githuba</a>, natomiast testy do nich <a href="hhttps://github.com/szogun1987/events-and-tasks/blob/master/src/Szogun1987.EventsAndTasks.Tests/NeverCalledBackTests.cs">tutaj</a>. Testy zwracają oczekiwany wynik tylko po zbudowaniu projektu w trybie Release, a właściwie to nie do końca zwracają. Test dla klasy FixedAdapter przechodzi i tak ma być. Test dla klasy BrokenAdapter nie przechodzi i to także jest zgodne z moimi oczekiwaniami.</p>
<p>Mam natomiast problem z testem dla klasy WorkedAroundAdapter, teoretycznie linijka Assert.NotNull(adapter) powinna sprawić że test przejdzie, ten jednak przejść nie chce i nie mam pojęcia dlaczego. Postanowiłem więc postawić znaczną ilość piwa, zgrzewkę 24 Tyskiego albo jego równowartość w innym gatunku, pierwszej osobie która mi to wytłumaczy.</p>